/**
 * @module server/pageStructure
 */

// Generated by https://quicktype.io

export interface PageStructure {
    story: Story
}

export interface Story {
    name: string
    created_at: string
    published_at: null
    alternates: any[]
    id: number
    uuid: string
    content: CmsContent
    slug: string
    full_slug: string
    default_full_slug: null
    sort_by_date: null
    position: number
    tag_list: any[]
    is_startpage: boolean
    parent_id: number
    meta_data: null
    group_id: string
    first_published_at: null
    release_id: null
    lang: string
    path: null
    translated_slugs: any[]
}}

export interface CmsContent {
    _uid: string
    body?: CmsContent[]
    component: string
    _editable: string
    name?: string
    headline?: string
    columns?: CmsContent[]
}
